runtime: python
env: flex
entrypoint: gunicorn -b :$PORT wishlist.wsgi

runtime_config:
  python_version: 3

env_variables:
  WISHLIST_DB_PW: your-password-here

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

manual_scaling:
  instances: 1

beta_settings:
  cloud_sql_instances: strong-province-113523:us-central1:travel-wishlist-db
